version: '3'
services:
  victoriametrics:
    image: victoriametrics/victoria-metrics
    ports:
      - "8428:8428"
  
  elasticsearch:
    image: elastic/elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
  
  otel-collector:
    image: otel/opentelemetry-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
  
  fluent-bit:
    image: fluent/fluent-bit
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    depends_on:
      - elasticsearch
  
  heracles-api:
    image: python:3.9
    command: bash -c "pip install flask python-json-logger && python app.py"
    volumes:
      - ./app.py:/app.py
    ports:
      - "5000:5000"

